### ISSUE TITLE
Mempool terminal client suddenly stopped working

### ISSUE THREAD

**Issue by jmacxx** [mempool/mempool-cli#1]
I love this little utility.  Its so neat to be able to check the mempool from the cli.  Recently, in the past couple of days it has stopped working.  I wonder if the mempool.space feed has changed. 

@wiz do you know if anything changed just recently in mempool.space that this utility would have to adapt to?

**Comment by wiz** [comment]
Ah yes, I suppose this app must have been connecting to our non-public API endpoint. Let's investigate how we can fix it @softsimon

**Comment by gchaincl** [comment]
I think the public API was updated, and mempool is connecting to the old endpoint.
@softsimon is the old v1 endpoint still alive?

**Comment by wiz** [comment]
we don't have any v1 backend running currently since the mempool.space site was upgraded to the v2 codebase yesterday

**Comment by gchaincl** [comment]
@jmacxx I'll need to update the code in order to use the v2 API.
I'll keep this open until fixed.

**Comment by wiz** [comment]
@gchaincl cool, maybe we should merge your command line app into the main mempool repo somehow, and then we can collaborate on the API together and synchronize the version numbers, etc. to avoid this from breaking again

**Comment by softsimon** [comment]
The major changes in the API is that you need to first push "init" to get an initial current state of all the data, and a "want" action with an array of what data you want to be pushed from there on.

https://mempool.space/contributors

Projected blocks has been renamed to mempool-blocks, and a new property called feeRange: number[] where the smallest and biggest number in that array is the same as the previous minFee and maxFee. 

The graph data is a pure list of objects now instead of using the fpv sub property.

There might be some small naming changes to the block properties like tx_count and also the unit of the fee. All to be consistent with the electrs backend.

**Comment by gchaincl** [comment]
> @gchaincl cool, maybe we should merge your command line app into the main mempool repo somehow, and then we can collaborate on the API together and synchronize the version numbers, etc. to avoid this from breaking again

I agree @wiz , how would you do that?

**Comment by gchaincl** [comment]
> The major changes in the API is that you need to first push "init" to get an initial current state of all the data, and a "want" action with an array of what data you want to be pushed from there on.
> 
> [mempool.space/contributors](https://mempool.space/contributors)
> 
> Projected blocks has been renamed to mempool-blocks, and a new property called feeRange: number[] where the smallest and biggest number in that array is the same as the previous minFee and maxFee.
> 
> The graph data is a pure list of objects now instead of using the fpv sub property.
> 
> There might be some small naming changes to the block properties like tx_count and also the unit of the fee. All to be consistent with the electrs backend.

Thanks @softsimon the changes you pointed out work

**Comment by gchaincl** [comment]
> I love this little utility. Its so neat to be able to check the mempool from the cli. Recently, in the past couple of days it has stopped working. I wonder if the mempool.space feed has changed.
> 
> @wiz do you know if anything changed just recently in mempool.space that this utility would have to adapt to?

Should be working now, check [v0.1.0](https://github.com/gchaincl/mempool/releases/tag/v0.1.0) or `docker run -it gchaincl/mempool:v0.1.0`

**Comment by wiz** [comment]
> I agree @wiz , how would you do that?

You could either submit this app as a PR to the main mempool repo in a subfolder, or if you want to keep it separate we could move this repo into the mempool organization and let you run it as a separate repo. We could also publish your docker image on the mempool docker account.

> Should be working now, check v0.1.0 

To sync the version numbers, can you tag your previous version that works on the mempool v1 backend as v1.0.0, and then tag the current / new version as v2.0.0 ? We haven't tagged the v2.0.0 release of mempool yet but we can do it now.

**Comment by gchaincl** [comment]
I'd move the code to https://github.com/mempool/mempool-cli if that makes sense. Once moved the repo, we could retag the releases accordingly.

**Comment by wiz** [comment]
Okay I invited you to the org, please initiate the transfer of this repo and did you want to join our Keybase team for chat? https://keybase.io/team/mempool

**Comment by gchaincl** [comment]
@jmacxx did you had the change to try the fix?

**Comment by jmacxx** [comment]
@gchaincl Yes it is working now, thanks very much!
